apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: fullstacktodo
  creationTimestamp: null
data:
  # username: server
  DATABASE_USERNAME: c2VydmVyCg==
  # password: password
  DATABASE_PASSWORD: cGFzc3dvcmQK


